---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rpi-boinc-deployment
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      deployment: rpi-boinc
  template:
    metadata:
      labels:
        deployment: rpi-boinc
    spec:
      containers:
        - name: boinc-client
          image: docker.io/boinc/client:arm64v8
          ports:
            - containerPort: 31416
          env:
            - name: BOINC_CMD_LINE_OPTIONS
              value: "--allow_remote_gui_rpc --attach_project https://boinc.bakerlab.org/rosetta 2425531_4bd35982e28034772b2fd36a926f9d01"
            - name: BOINC_GUI_RPC_PASSWORD
              value: "password"
          resources:
            requests:
              cpu: "1000m"
              memory: "512Mi"
            limits:
              memory: "2048Mi"
          volumeMounts:
            - name: boinc-data
              mountPath: /var/lib/boinc
      volumes:
        - name: boinc-data
          emptyDir: {}
