---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rpi-boinc-deployment
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      deployment: rpi-boinc
  template:
    metadata:
      labels:
        deployment: rpi-boinc
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: deployment
                    operator: In
                    values:
                      - rpi-boinc
              topologyKey: kubernetes.io/hostname
      containers:
        - name: boinc-client
          image: docker.io/boinc/client:arm64v8
          ports:
            - containerPort: 31416
          env:
            - name: BOINC_ACCOUNT_KEY
              valueFrom:
                secretKeyRef:
                  name: rpi-boinc-secret
                  key: account-key
            - name: BOINC_CMD_LINE_OPTIONS
              value: "--allow_remote_gui_rpc --attach_project https://boinc.bakerlab.org/rosetta $(BOINC_ACCOUNT_KEY)"
            - name: BOINC_GUI_RPC_PASSWORD
              value: "password"
          resources:
            requests:
              cpu: "500m"
              memory: "512Mi"
            limits:
              cpu: "1000m"
              memory: "1024Mi"
          volumeMounts:
            - name: boinc-data
              mountPath: /var/lib/boinc
      volumes:
        - name: boinc-data
          emptyDir: {}
