---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: rpi-boinc
  namespace: default
commonLabels:
  app: rpi-boinc
resources:
  - secret.yaml
  - deployment.yaml
  - service.yaml
